#ifndef CPYTHON_APPROXIMATION_DEFS_H
#define CPYTHON_APPROXIMATION_DEFS_H


PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_LEN;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_ISINSTANCE;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_LIST_APPEND;

#endif //CPYTHON_APPROXIMATION_DEFS_H
