#ifndef CPYTHON_APPROXIMATION_DEFS_H
#define CPYTHON_APPROXIMATION_DEFS_H


PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_LEN;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_ISINSTANCE;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_MIN;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_MAX;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_ALL;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_SUM;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_LIST_APPEND;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_LIST_POP;

#endif //CPYTHON_APPROXIMATION_DEFS_H
