#ifndef CPYTHON_APPROXIMATION_DEFS_H
#define CPYTHON_APPROXIMATION_DEFS_H


PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_LEN;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_ISINSTANCE;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_MIN;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_MAX;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_ALL;
PyAPI_DATA(void *) EXPORT_FOR_APPROXIMATION_BUILTIN_SUM;

PyAPI_DATA(void *) EXPORT_OBJECT_INIT;
PyAPI_DATA(void *) EXPORT_SLOT_INIT;

#endif //CPYTHON_APPROXIMATION_DEFS_H
